import { appendCurriculumWorld, createCurriculumTrack } from "../_shared/defineLesson";
import { outputBonus, outputTask } from "../_shared/taskBuilders";
import { javascriptV4World } from "../v4/javascriptWorld";
import { javascriptV5World } from "./v5World";
import { javascriptProductWorld } from "./productWorld";

const jsTask = (
  id: string,
  title: string,
  description: string,
  expectedBehavior: string,
  starterCode: string,
  expected: string,
  hints: string[],
  defaultInput?: string,
) =>
  outputTask(
    {
      id,
      title,
      description,
      expectedBehavior,
      starterCode,
      hints,
      ...(defaultInput ? { defaultInput } : {}),
    },
    expected,
  );

const jsBonus = (
  id: string,
  title: string,
  description: string,
  expectedBehavior: string,
  starterCode: string,
  expected: string,
  hints: string[],
  discoveryText: string,
  defaultInput?: string,
) =>
  outputBonus(
    {
      id,
      title,
      description,
      expectedBehavior,
      starterCode,
      hints,
      ...(defaultInput ? { defaultInput } : {}),
    },
    expected,
    discoveryText,
  );

const baseTrack = createCurriculumTrack({
  id: "javascript",
  order: 2,
  language: "JavaScript",
  title: "Reactive Signal",
  archiveName: "The Event Lattice",
  description:
    "Learn modern JavaScript from values and control flow through objects, transformations, JSON, and asynchronous signals.",
  icon: "JS",
  accent: "amber",
  execution: {
    kind: "javascript",
    editorLanguage: "javascript",
    fileExtension: "js",
    supportsStdin: true,
    actionLabel: "Run & validate",
    runtimeLabel: "JavaScript Worker",
  },
  worlds: [
    {
      id: "signal-circuit",
      title: "Signal Circuit",
      subtitle: "The language foundations that power browser behavior",
      description:
        "Values, variables, arrays, decisions, and iteration form the first live circuit in the Event Lattice.",
      landmark: "The Console Beacon",
      accent: "amber",
      lessons: [
        {
          id: "javascript-first-signal",
          title: "Console Ignition",
          subtitle: "Run JavaScript and observe values",
          objectives: [
            "Call console.log",
            "Distinguish strings, numbers, and booleans",
            "Read execution output",
          ],
          conceptHeading: "Values enter the lattice through expressions",
          explanation: [
            "JavaScript evaluates expressions into values. Strings represent text, numbers represent numeric quantities, and booleans represent true or false decisions.",
            "console.log sends one or more values to the practice console. It is useful for visible results and for inspecting intermediate state.",
          ],
          bullets: [
            "Strings use quotes or backticks.",
            "Numbers support arithmetic operators.",
            "typeof reports a value's runtime type.",
          ],
          syntax: 'console.log("Signal online");',
          example: {
            title: "Three visible values",
            description: "The console renders each logged value on its own line.",
            code: 'console.log("NEXUS");\nconsole.log(6 * 7);\nconsole.log(true);',
            output: "NEXUS\n42\ntrue",
          },
          fieldNote:
            "Use logging to observe a program, then remove temporary diagnostics when output must follow an exact contract.",
          mistakes: [
            "Writing Console.log with the wrong letter case.",
            "Omitting quotes around literal text.",
            "Confusing the string '42' with the number 42.",
          ],
          tasks: [
            jsTask(
              "javascript-first-signal-output",
              "Transmit two values",
              "Print Event Lattice and then 21 + 21.",
              "Print Event Lattice then 42.",
              "// Send the archive label and recovered value\n",
              "Event Lattice\n42",
              ["Use two console.log calls."],
            ),
            jsTask(
              "javascript-first-signal-types",
              "Inspect runtime types",
              'Print typeof "signal", typeof 88, and typeof false.',
              "Print string, number, boolean.",
              '// Inspect three values\nconsole.log(typeof "signal");\n',
              "string\nnumber\nboolean",
              ["typeof is an operator, not a function requirement."],
            ),
          ],
          bonusTask: jsBonus(
            "javascript-first-signal-bonus",
            "Input echo",
            "Read one line with input(), uppercase it, and print SIGNAL:<value>.",
            "For nexus print SIGNAL:NEXUS.",
            "const raw = input();\n// Normalize and transmit\n",
            "SIGNAL:NEXUS",
            ["Strings provide toUpperCase()."],
            "The Console Beacon answers a user-provided transmission.",
            "nexus",
          ),
        },
        {
          id: "javascript-variables",
          title: "Binding Nodes",
          subtitle: "Name values with const and let",
          objectives: [
            "Declare const and let bindings",
            "Update a let binding",
            "Interpolate values with template literals",
          ],
          conceptHeading: "Bindings give changing and stable values useful names",
          explanation: [
            "Use const when a binding will not be reassigned and let when it must point to a new value later. Both are block-scoped and safer than the older var declaration.",
            "Template literals use backticks and ${expression} placeholders to combine text with live values without manual concatenation.",
          ],
          bullets: [
            "Default to const.",
            "Use let only for deliberate reassignment.",
            "Choose names that describe meaning, not storage type.",
          ],
          syntax: 'const name = "Prism";\nlet energy = 40;\nenergy += 2;',
          example: {
            title: "Update an energy reading",
            description: "The binding changes before it enters the template.",
            code: 'const relic = "Prism";\nlet energy = 80;\nenergy += 8;\nconsole.log(`${relic}:${energy}`);',
            output: "Prism:88",
          },
          fieldNote:
            "const protects the binding from reassignment; it does not make an array or object deeply immutable.",
          mistakes: [
            "Reassigning a const binding.",
            "Using ${...} inside normal quote strings.",
            "Creating multiple names for one simple value.",
          ],
          tasks: [
            jsTask(
              "javascript-variables-energy",
              "Update signal energy",
              "Start energy at 35, add 7, and print ENERGY=42 with a template literal.",
              "Print ENERGY=42.",
              "let energy = 35;\n// Update and report\n",
              "ENERGY=42",
              ["Use energy += 7 and a backtick string."],
            ),
            jsTask(
              "javascript-variables-profile",
              "Compose a profile label",
              "Declare name Atlas and level 4 as const values, then print Atlas / LV-04.",
              "Print Atlas / LV-04.",
              "// Declare stable profile values\n",
              "Atlas / LV-04",
              ["The displayed zero can be part of the template text."],
            ),
          ],
          bonusTask: jsBonus(
            "javascript-variables-bonus",
            "Coordinate decoder",
            "Read sector and fragment on separate lines and print NX-sector:fragment with each number padded to two digits.",
            "For 3 and 7 print NX-03:07.",
            "const sector = input();\nconst fragment = input();\n// Pad and report\n",
            "NX-03:07",
            ['Use padStart(2, "0") on each input string.'],
            "A precise coordinate appears inside the Binding Nodes.",
            "3\n7",
          ),
        },
        {
          id: "javascript-arrays",
          title: "Sequence Rails",
          subtitle: "Store and transform ordered values",
          objectives: [
            "Create and index arrays",
            "Add values with push",
            "Use slice and join for reports",
          ],
          conceptHeading: "Arrays preserve an ordered sequence of values",
          explanation: [
            "An array stores values under zero-based numeric indexes. Its length changes as values are added or removed, and its methods express common sequence operations.",
            "Prefer non-mutating methods such as slice when you need a derived sequence while preserving the original.",
          ],
          bullets: [
            "The first index is 0.",
            "length is a property.",
            "join converts values into one formatted string.",
          ],
          syntax: 'const signals = ["NX", "Echo"];\nsignals.push("Atlas");',
          example: {
            title: "Extend a call-sign rail",
            description: "push appends and join builds stable output.",
            code: 'const calls = ["NX", "Echo"];\ncalls.push("Atlas");\nconsole.log(calls.join(" > "));',
            output: "NX > Echo > Atlas",
          },
          fieldNote:
            "Check both array contents and array length when diagnosing indexing errors.",
          mistakes: [
            "Reading array[array.length] and getting undefined.",
            "Calling length as if it were a function.",
            "Expecting push to return the array instead of its new length.",
          ],
          tasks: [
            jsTask(
              "javascript-arrays-append",
              "Extend the rail",
              "Append coil and prism, then print key|coil|prism.",
              "Print key|coil|prism.",
              'const relics = ["key"];\n// Append two values and join\n',
              "key|coil|prism",
              ["Call push once with both values or twice."],
            ),
            jsTask(
              "javascript-arrays-slice",
              "Extract a safe window",
              "Use slice to select indexes 1 through 3 from [3,8,13,21,34] and join with commas.",
              "Print 8,13,21.",
              "const values = [3, 8, 13, 21, 34];\n// Slice without changing values\n",
              "8,13,21",
              ["The slice end index is exclusive."],
            ),
          ],
          bonusTask: jsBonus(
            "javascript-arrays-bonus",
            "Queue rotation",
            "Move the first item to the end of [NX,Echo,Atlas] and print Echo > Atlas > NX.",
            "Print Echo > Atlas > NX.",
            'const queue = ["NX", "Echo", "Atlas"];\n// Remove first, append it, and report\n',
            "Echo > Atlas > NX",
            ["shift removes and returns the first value; push appends it."],
            "The Sequence Rails complete a circular route.",
          ),
        },
        {
          id: "javascript-conditions",
          title: "Decision Gates",
          subtitle: "Route values through boolean conditions",
          objectives: [
            "Write if / else if / else",
            "Use strict equality",
            "Combine boolean conditions",
          ],
          conceptHeading: "A condition chooses which block can run",
          explanation: [
            "if executes a block only when its expression is truthy. else if adds ordered alternatives, and else provides a final fallback.",
            "Use === and !== for predictable equality without automatic type conversion. Combine independent requirements with && and alternatives with ||.",
          ],
          bullets: [
            "Order thresholds from most restrictive to least.",
            "Prefer strict equality.",
            "Keep each branch's purpose visible.",
          ],
          syntax:
            'if (energy >= 80) {\n  console.log("high");\n} else {\n  console.log("stable");\n}',
          example: {
            title: "Classify one reading",
            description: "The first matching branch wins.",
            code: 'const energy = 61;\nif (energy >= 80) {\n  console.log("high");\n} else if (energy >= 40) {\n  console.log("stable");\n} else {\n  console.log("faint");\n}',
            output: "stable",
          },
          fieldNote:
            "Write boundary examples beside a condition: one below, exactly equal, and one above.",
          mistakes: [
            "Using = instead of an equality operator.",
            "Testing a lower threshold before a higher one.",
            "Relying on truthiness when zero is a valid value.",
          ],
          tasks: [
            jsTask(
              "javascript-conditions-band",
              "Classify three energies",
              "Print high for 80+, stable for 40+, faint otherwise for 91, 55, 12.",
              "Print high, stable, faint.",
              "for (const energy of [91, 55, 12]) {\n  // Classify energy\n}",
              "high\nstable\nfaint",
              ["Use an if / else if / else chain inside the loop."],
            ),
            jsTask(
              "javascript-conditions-access",
              "Check compound access",
              "Access is granted when active is true and clearance is at least 3.",
              "For true/4 and true/2 print GRANTED then DENIED.",
              "const attempts = [[true, 4], [true, 2]];\nfor (const [active, clearance] of attempts) {\n  // Print GRANTED or DENIED\n}",
              "GRANTED\nDENIED",
              ["Combine both conditions with &&."],
            ),
          ],
          bonusTask: jsBonus(
            "javascript-conditions-bonus",
            "Protocol router",
            "Read a protocol and route py/js to EXECUTE, html/css to RENDER, and anything else to INSPECT.",
            "For html print RENDER.",
            "const protocol = input().trim().toLowerCase();\n// Route the protocol\n",
            "RENDER",
            ["Use || for the two values in each route."],
            "A new branch illuminates inside the Decision Gates.",
            "html",
          ),
        },
        {
          id: "javascript-loops",
          title: "Iteration Orbit",
          subtitle: "Repeat work over sequences",
          objectives: [
            "Iterate values with for...of",
            "Track an accumulator",
            "Use continue and break deliberately",
          ],
          conceptHeading: "Loops apply one rule across many values",
          explanation: [
            "for...of reads array values directly and is the default choice when indexes are not needed. An accumulator such as total carries a result across iterations.",
            "continue skips the rest of the current iteration; break exits the loop completely. Use them when they make the control flow clearer.",
          ],
          bullets: [
            "Initialize accumulators before the loop.",
            "Update them inside the loop.",
            "Report after the loop unless each step is required.",
          ],
          syntax: "let total = 0;\nfor (const value of values) {\n  total += value;\n}",
          example: {
            title: "Aggregate readings",
            description: "One accumulator gathers the complete sequence.",
            code: "let total = 0;\nfor (const value of [4, 8, 15]) {\n  total += value;\n}\nconsole.log(total);",
            output: "27",
          },
          fieldNote:
            "Trace the accumulator after each iteration on paper when a loop result is surprising.",
          mistakes: [
            "Resetting the accumulator inside the loop.",
            "Using for...in and receiving array indexes as strings.",
            "Creating a loop whose stop condition never changes.",
          ],
          tasks: [
            jsTask(
              "javascript-loops-total",
              "Sum valid readings",
              "Sum only non-negative values from [4,-2,8,-1,5].",
              "Print 17.",
              "let total = 0;\nfor (const value of [4, -2, 8, -1, 5]) {\n  // Skip negative readings\n}\nconsole.log(total);",
              "17",
              ["continue can skip negative values."],
            ),
            jsTask(
              "javascript-loops-first",
              "Stop at the first match",
              "Find and print the first value above 50.",
              "For [12,44,71,88] print 71 once.",
              "for (const value of [12, 44, 71, 88]) {\n  // Print first match and stop\n}",
              "71",
              ["Use break immediately after logging the match."],
            ),
          ],
          bonusTask: jsBonus(
            "javascript-loops-bonus",
            "Frequency relay",
            "Count normalized call signs and print nx=3 and echo=1.",
            "For NX nx Echo NX print nx=3 and echo=1.",
            'const calls = ["NX", "nx", "Echo", "NX"];\nconst counts = {};\n// Count and report\n',
            "nx=3\necho=1",
            ["Use counts[key] = (counts[key] ?? 0) + 1."],
            "The Iteration Orbit settles into a stable cycle.",
          ),
        },
      ],
    },
    {
      id: "reactive-lattice",
      title: "Reactive Lattice",
      subtitle: "Functions and data structures for modern application logic",
      description:
        "Reusable functions, objects, array transformations, JSON boundaries, and promises connect JavaScript into a responsive system.",
      landmark: "The Promise Relay",
      accent: "violet",
      lessons: [
        {
          id: "javascript-functions",
          title: "Function Relays",
          subtitle: "Package behavior behind clear inputs and outputs",
          objectives: [
            "Declare and call functions",
            "Return values",
            "Write concise arrow functions",
          ],
          conceptHeading: "A function turns an explicit input into reusable behavior",
          explanation: [
            "Functions name a calculation or operation so it can be tested and reused. Parameters receive input and return sends a result back to the caller.",
            "Arrow functions are compact and common in callbacks. Function declarations remain excellent for major named operations.",
          ],
          bullets: [
            "Keep one responsibility per function.",
            "Return values instead of relying on global state.",
            "Name functions with action verbs.",
          ],
          syntax: "function boost(value) {\n  return value * 2;\n}",
          example: {
            title: "Reusable formatter",
            description: "The returned string can be logged or composed elsewhere.",
            code: 'function label(name, energy) {\n  return `${name}:${energy}`;\n}\nconsole.log(label("Prism", 88));',
            output: "Prism:88",
          },
          fieldNote:
            "A function is easiest to test when it returns a value and does not depend on hidden external state.",
          mistakes: [
            "Logging a result but forgetting to return it.",
            "Calling a function with parameters in the wrong order.",
            "Using an arrow expression with braces but no return.",
          ],
          tasks: [
            jsTask(
              "javascript-functions-clamp",
              "Clamp a reading",
              "Write clamp(value,min,max) and test -4, 42, 130 in range 0..100.",
              "Print 0, 42, 100.",
              "function clamp(value, min, max) {\n  // Return bounded value\n}\n\nfor (const value of [-4, 42, 130]) {\n  console.log(clamp(value, 0, 100));\n}",
              "0\n42\n100",
              ["Math.min and Math.max can be nested."],
            ),
            jsTask(
              "javascript-functions-arrow",
              "Map through an arrow",
              "Create an arrow function double and map [2,5,8].",
              "Print 4|10|16.",
              '// Declare double as an arrow function\nconst values = [2, 5, 8];\nconsole.log(values.map(double).join("|"));',
              "4|10|16",
              ["A single expression can be returned implicitly."],
            ),
          ],
          bonusTask: jsBonus(
            "javascript-functions-bonus",
            "Configurable formatter",
            "Create formatReading(name,value,unit='u') and print Prism / 88u then Echo / 12db.",
            "Print both formatted readings.",
            'function formatReading(name, value, unit = "u") {\n  // Return formatted text\n}\n\nconsole.log(formatReading("Prism", 88));\nconsole.log(formatReading("Echo", 12, "db"));',
            "Prism / 88u\nEcho / 12db",
            ["Use a default parameter and a template literal."],
            "The Function Relays begin transmitting reusable behavior.",
          ),
        },
        {
          id: "javascript-objects",
          title: "Object Observatory",
          subtitle: "Model labeled state and methods",
          objectives: [
            "Create object literals",
            "Read and update properties",
            "Define methods using this",
          ],
          conceptHeading: "Objects collect named properties under one identity",
          explanation: [
            "An object literal models a concept with key-value properties. Dot notation reads known property names; bracket notation is useful for computed keys.",
            "Methods can read the current object through this. Keep object state coherent by routing repeated updates through a method.",
          ],
          bullets: [
            "Use meaningful property names.",
            "Use bracket access for dynamic keys.",
            "Avoid arrow functions when a method needs dynamic this.",
          ],
          syntax: 'const signal = { name: "NX", energy: 80 };',
          example: {
            title: "State-changing method",
            description: "The method owns its update rule.",
            code: "const cell = {\n  energy: 30,\n  charge(amount) {\n    this.energy += amount;\n    return this.energy;\n  },\n};\nconsole.log(cell.charge(12));",
            output: "42",
          },
          fieldNote:
            "Use an object when labels add meaning that positional array indexes cannot express.",
          mistakes: [
            "Reading a misspelled property and receiving undefined.",
            "Using this outside the method context you expect.",
            "Mutating shared objects from unrelated parts of a program.",
          ],
          tasks: [
            jsTask(
              "javascript-objects-relic",
              "Build a relic object",
              "Create a relic with name Prism and energy 88, then print Prism:88.",
              "Print Prism:88.",
              "const relic = {\n  // Add properties\n};\nconsole.log(`${relic.name}:${relic.energy}`);",
              "Prism:88",
              ["Object properties use key: value pairs."],
            ),
            jsTask(
              "javascript-objects-method",
              "Protect an energy update",
              "Add charge(amount) that caps cell.energy at 100. Charge 85 by 30.",
              "Print 100.",
              "const cell = {\n  energy: 85,\n  charge(amount) {\n    // Update and return this.energy\n  },\n};\nconsole.log(cell.charge(30));",
              "100",
              ["Use Math.min(100, this.energy + amount)."],
            ),
          ],
          bonusTask: jsBonus(
            "javascript-objects-bonus",
            "Dynamic inventory",
            "Count prism, key, prism in an object and print prism=2 and key=1.",
            "Print both counts.",
            'const items = ["prism", "key", "prism"];\nconst inventory = {};\n// Build dynamic keys and report\n',
            "prism=2\nkey=1",
            ["Use inventory[item] with ?? 0."],
            "The Object Observatory resolves named state into a searchable map.",
          ),
        },
        {
          id: "javascript-array-methods",
          title: "Transformation Array",
          subtitle: "Compose map, filter, reduce, and find",
          objectives: [
            "Transform values with map",
            "Select values with filter",
            "Aggregate values with reduce",
          ],
          conceptHeading: "Array methods describe data flow without manual indexes",
          explanation: [
            "map produces one output per input, filter keeps selected inputs, and reduce combines a sequence into one accumulated result. These methods accept callback functions.",
            "Chaining is readable when each step has a clear purpose. Store intermediate arrays when a long chain becomes difficult to inspect.",
          ],
          bullets: [
            "map preserves length.",
            "filter may shorten the array.",
            "reduce needs a deliberate initial value.",
          ],
          syntax: "values.filter(test).map(transform).reduce(combine, initial)",
          example: {
            title: "Process valid energy",
            description: "Each method owns one pipeline stage.",
            code: "const total = [10, -2, 30]\n  .filter((value) => value >= 0)\n  .map((value) => value * 2)\n  .reduce((sum, value) => sum + value, 0);\nconsole.log(total);",
            output: "80",
          },
          fieldNote:
            "Name callbacks when their rule cannot be understood immediately from a short expression.",
          mistakes: [
            "Forgetting return in a callback with braces.",
            "Using map when only a side effect is needed.",
            "Reducing without a safe initial value.",
          ],
          tasks: [
            jsTask(
              "javascript-array-methods-pipeline",
              "Filter and boost",
              "Keep even values from [1,2,3,4,5,6], triple them, and join with commas.",
              "Print 6,12,18.",
              "const values = [1, 2, 3, 4, 5, 6];\n// Filter, map, and report\n",
              "6,12,18",
              ["Chain filter before map."],
            ),
            jsTask(
              "javascript-array-methods-total",
              "Reduce total energy",
              "Sum energy properties from three records.",
              "Print 179.",
              "const records = [{ energy: 30 }, { energy: 88 }, { energy: 61 }];\n// Reduce with initial value 0\n",
              "179",
              ["The callback returns sum + record.energy."],
            ),
          ],
          bonusTask: jsBonus(
            "javascript-array-methods-bonus",
            "Rank active records",
            "Keep active records, sort by score descending, and print Atlas:91|Nexus:77.",
            "Print Atlas:91|Nexus:77.",
            'const records = [\n  { name: "Nexus", score: 77, active: true },\n  { name: "Echo", score: 99, active: false },\n  { name: "Atlas", score: 91, active: true },\n];\n// Filter, sort, map, and join\n',
            "Atlas:91|Nexus:77",
            [
              "sort can compare b.score - a.score.",
              "map each record to a template literal.",
            ],
            "A complete transformation channel lights across the lattice.",
          ),
        },
        {
          id: "javascript-json-errors",
          title: "Boundary Decoder",
          subtitle: "Parse JSON and contain malformed data",
          objectives: [
            "Serialize data with JSON.stringify",
            "Parse JSON with JSON.parse",
            "Catch a SyntaxError boundary failure",
          ],
          conceptHeading: "JSON is a text boundary, not a live JavaScript object",
          explanation: [
            "JSON.stringify turns supported JavaScript data into portable text. JSON.parse reconstructs values from valid JSON text.",
            "External JSON may be malformed or structurally unexpected. Catch parsing failures, then validate required fields before the data enters application logic.",
          ],
          bullets: [
            "JSON keys and strings use double quotes.",
            "Functions and undefined are not JSON data.",
            "Treat parsed values as untrusted input.",
          ],
          syntax: "const data = JSON.parse(text);",
          example: {
            title: "Protected parsing",
            description: "Malformed text receives an explicit recovery path.",
            code: 'for (const raw of [\'{"energy":42}\', "{broken"]) {\n  try {\n    console.log(JSON.parse(raw).energy);\n  } catch (error) {\n    console.log("INVALID");\n  }\n}',
            output: "42\nINVALID",
          },
          fieldNote:
            "A successful parse guarantees valid JSON syntax, not that the object has the fields or types your program requires.",
          mistakes: [
            "Writing single-quoted keys inside JSON text.",
            "Assuming parsed fields always exist.",
            "Catching an error and silently discarding every record.",
          ],
          tasks: [
            jsTask(
              "javascript-json-errors-parse",
              "Decode a record",
              "Parse the supplied JSON and print Prism:88.",
              "Print Prism:88.",
              'const raw = \'{"name":"Prism","energy":88}\';\n// Parse and report\n',
              "Prism:88",
              ["JSON.parse returns the object."],
            ),
            jsTask(
              "javascript-json-errors-catch",
              "Contain malformed JSON",
              "Parse both strings and print the id, or INVALID when parsing fails.",
              "Print 7 then INVALID.",
              'const payloads = [\'{"id":7}\', "{broken"];\nfor (const raw of payloads) {\n  // Parse safely\n}',
              "7\nINVALID",
              ["Wrap JSON.parse in try/catch."],
            ),
          ],
          bonusTask: jsBonus(
            "javascript-json-errors-bonus",
            "Validated payload intake",
            "Parse three payloads and accept only objects with a string name and numeric score from 0 to 100.",
            "Print ACCEPT:Atlas then REJECT twice.",
            'const payloads = [\n  \'{"name":"Atlas","score":91}\',\n  \'{"name":"Echo","score":140}\',\n  "broken",\n];\n// Parse, validate shape and range, then report\n',
            "ACCEPT:Atlas\nREJECT\nREJECT",
            [
              "Use typeof for fields and && for the range.",
              "The catch path also prints REJECT.",
            ],
            "The Boundary Decoder rejects corrupted transmissions without losing the circuit.",
          ),
        },
        {
          id: "javascript-async",
          title: "Promise Relay",
          subtitle: "Coordinate values that arrive later",
          objectives: [
            "Create and await a Promise",
            "Write an async function",
            "Contain rejected promises",
          ],
          conceptHeading: "A Promise represents a future completion or failure",
          explanation: [
            "An async function always returns a Promise. await pauses that function until the Promise settles without blocking the browser's main interface.",
            "Rejected promises behave like thrown errors around await, so use try/catch at a boundary that can provide a meaningful recovery path.",
          ],
          bullets: [
            "await is available inside async functions and this lesson runner.",
            "Return values become fulfilled Promise values.",
            "Catch failures where you can explain or recover from them.",
          ],
          syntax:
            "async function recover() {\n  const value = await Promise.resolve(42);\n  return value;\n}",
          example: {
            title: "Await a recovered value",
            description: "The worker waits for the Promise and logs its value.",
            code: 'async function recover() {\n  return Promise.resolve("online");\n}\nconsole.log(await recover());',
            output: "online",
          },
          fieldNote:
            "Asynchronous does not mean parallel CPU work; it primarily coordinates waiting without freezing the interface.",
          mistakes: [
            "Forgetting await and logging a Promise object.",
            "Using await in a non-async function.",
            "Ignoring a rejection and creating an unhandled failure.",
          ],
          tasks: [
            jsTask(
              "javascript-async-resolve",
              "Await signal energy",
              "Await Promise.resolve(42) and print ENERGY=42.",
              "Print ENERGY=42.",
              "const energyPromise = Promise.resolve(42);\n// Await and report\n",
              "ENERGY=42",
              ["The lesson worker supports top-level await."],
            ),
            jsTask(
              "javascript-async-function",
              "Compose an async function",
              "Write async recover(name) that awaits the name and returns uppercase.",
              "For prism print PRISM.",
              'async function recover(name) {\n  // Await a resolved name and return uppercase\n}\n\nconsole.log(await recover("prism"));',
              "PRISM",
              ["Store await Promise.resolve(name), then transform it."],
            ),
          ],
          bonusTask: jsBonus(
            "javascript-async-bonus",
            "Rejected channel recovery",
            "Await three promises in order and print their values; print RECOVERED for the rejected one.",
            "Print NX, RECOVERED, Atlas.",
            'const channels = [\n  Promise.resolve("NX"),\n  Promise.reject(new Error("lost")),\n  Promise.resolve("Atlas"),\n];\n\nfor (const channel of channels) {\n  // Await safely and report\n}',
            "NX\nRECOVERED\nAtlas",
            ["Use try/catch inside the loop so later channels still run."],
            "The Promise Relay stays responsive through both completion and failure.",
          ),
          durationMinutes: 32,
        },
      ],
    },
  ],
  futureWorlds: ["DOM Interface", "Web API Observatory", "Network Channels"],
});

export const track = appendCurriculumWorld(
  appendCurriculumWorld(
    appendCurriculumWorld(baseTrack, javascriptV4World),
    javascriptV5World,
  ),
  javascriptProductWorld,
);
