import type { Achievement } from "../types";

export const achievements: Achievement[] = [
  {
    id: "first-recovered-signal",
    name: "First Recovered Signal",
    description: "Stabilize your first practice transmission.",
    rarity: "common",
    icon: "signal",
    condition: { type: "task-count", count: 1 },
    discoveryText: "A faint pulse answers from the archive.",
  },
  {
    id: "fragment-reader",
    name: "Fragment Reader",
    description: "Restore your first complete lesson fragment.",
    rarity: "common",
    icon: "fragment",
    condition: { type: "lesson-count", count: 1 },
  },
  {
    id: "logic-excavator",
    name: "Logic Excavator",
    description: "Recover the entire Logic Chambers sector.",
    rarity: "rare",
    icon: "compass",
    condition: {
      type: "world-completed",
      trackId: "python",
      worldId: "logic-chambers",
    },
    discoveryText: "Conditional pathways converge into a stable reasoning lattice.",
  },
  {
    id: "loop-resonator",
    name: "Loop Resonator",
    description: "Complete the loop reconstruction fragment.",
    rarity: "uncommon",
    icon: "orbit",
    condition: { type: "lesson-completed", lessonId: "python-loops" },
  },
  {
    id: "memory-cartographer",
    name: "Memory Cartographer",
    description: "Map every fragment inside Memory Structures.",
    rarity: "rare",
    icon: "map",
    condition: {
      type: "world-completed",
      trackId: "python",
      worldId: "memory-structures",
    },
  },
  {
    id: "hidden-channel",
    name: "Hidden Channel",
    description: "Recover three optional bonus transmissions.",
    rarity: "uncommon",
    icon: "key",
    condition: { type: "bonus-count", count: 3 },
  },
  {
    id: "pulse-keeper",
    name: "Pulse Keeper",
    description: "Maintain a three-day Pulse Chain.",
    rarity: "rare",
    icon: "pulse",
    condition: { type: "streak", days: 3 },
  },
  {
    id: "archive-restorer",
    name: "Archive Restorer",
    description: "Restore the complete Python Core expedition.",
    rarity: "mythic",
    icon: "core",
    condition: { type: "track-completed", trackId: "python" },
    discoveryText: "The dormant organism recognizes you as a core restorer.",
  },
  {
    id: "signal-conductor",
    name: "Signal Conductor",
    description: "Accumulate 1,000 units of recovered Signal Energy.",
    rarity: "mythic",
    icon: "conductor",
    condition: { type: "total-xp", amount: 1000 },
  },
  {
    id: "flow-surveyor",
    name: "Flow Surveyor",
    description: "Restore the complete Data Currents sector.",
    rarity: "rare",
    icon: "current",
    condition: {
      type: "world-completed",
      trackId: "python",
      worldId: "data-currents",
    },
  },
  {
    id: "object-smith",
    name: "Object Smith",
    description: "Complete every blueprint in the Object Foundry.",
    rarity: "rare",
    icon: "blueprint",
    condition: {
      type: "world-completed",
      trackId: "python",
      worldId: "object-foundry",
    },
  },
  {
    id: "algorithm-observer",
    name: "Algorithm Observer",
    description: "Complete the Algorithm Observatory sector.",
    rarity: "mythic",
    icon: "orrery",
    condition: {
      type: "world-completed",
      trackId: "python",
      worldId: "algorithm-observatory",
    },
  },
  {
    id: "event-conductor",
    name: "Event Conductor",
    description: "Restore the complete JavaScript expedition.",
    rarity: "mythic",
    icon: "relay",
    condition: { type: "track-completed", trackId: "javascript" },
  },
  {
    id: "interface-archaeologist",
    name: "Interface Archaeologist",
    description: "Restore the complete HTML / CSS expedition.",
    rarity: "mythic",
    icon: "strata",
    condition: { type: "track-completed", trackId: "html-css" },
  },
  {
    id: "class-curator",
    name: "Class Curator",
    description: "Restore the Java Typed Reliquary.",
    rarity: "rare",
    icon: "class",
    condition: { type: "track-completed", trackId: "java" },
  },
  {
    id: "machine-cartographer",
    name: "Machine Cartographer",
    description: "Restore the C++ Memory Engine.",
    rarity: "rare",
    icon: "memory",
    condition: { type: "track-completed", trackId: "cpp" },
  },
  {
    id: "deep-recovery",
    name: "Deep Recovery",
    description: "Restore 20 complete lesson fragments.",
    rarity: "rare",
    icon: "depth",
    condition: { type: "lesson-count", count: 20 },
  },
  {
    id: "polyglot-core",
    name: "Polyglot Core",
    description: "Restore 40 complete lesson fragments across the archive.",
    rarity: "mythic",
    icon: "polyglot",
    condition: { type: "lesson-count", count: 40 },
  },
  {
    id: "hidden-network",
    name: "Hidden Network",
    description: "Recover twelve optional bonus transmissions.",
    rarity: "rare",
    icon: "network",
    condition: { type: "bonus-count", count: 12 },
  },
  {
    id: "seven-day-orbit",
    name: "Seven-Day Orbit",
    description: "Maintain a seven-day Pulse Chain.",
    rarity: "mythic",
    icon: "orbit-seven",
    condition: { type: "streak", days: 7 },
  },
  {
    id: "archive-reactor",
    name: "Archive Reactor",
    description: "Accumulate 3,000 units of Signal Energy.",
    rarity: "mythic",
    icon: "reactor",
    condition: { type: "total-xp", amount: 3000 },
  },
  {
    id: "boundary-witness",
    name: "Boundary Witness",
    description: "Complete the Verification Chamber and stabilize its executable tests.",
    rarity: "uncommon",
    icon: "verification",
    condition: {
      type: "lesson-completed",
      lessonId: "python-testing-assertions",
    },
  },
  {
    id: "systems-field-engineer",
    name: "Systems Field Engineer",
    description: "Restore every fragment inside the Systems Laboratory.",
    rarity: "mythic",
    icon: "engine",
    condition: {
      type: "world-completed",
      trackId: "python",
      worldId: "systems-laboratory",
    },
    discoveryText: "The Verification Engine accepts your complete operational protocol.",
  },
  {
    id: "archive-master-index",
    name: "Master Index",
    description: "Restore sixty lesson fragments across the complete archive.",
    rarity: "mythic",
    icon: "index",
    condition: { type: "lesson-count", count: 60 },
  },
  {
    id: "graph-pathfinder",
    name: "Graph Pathfinder",
    description: "Restore every route inside the Python Graph Nexus.",
    rarity: "mythic",
    icon: "map",
    condition: {
      type: "world-completed",
      trackId: "python",
      worldId: "graph-nexus",
    },
    discoveryText: "Every weighted route converges on a verified optimal path.",
  },
  {
    id: "temporal-conductor",
    name: "Temporal Conductor",
    description: "Restore the JavaScript State Reactor.",
    rarity: "rare",
    icon: "orbit",
    condition: {
      type: "world-completed",
      trackId: "javascript",
      worldId: "state-reactor",
    },
  },
  {
    id: "adaptive-prism",
    name: "Adaptive Prism",
    description: "Restore the HTML/CSS Interface Reactor.",
    rarity: "rare",
    icon: "compass",
    condition: {
      type: "world-completed",
      trackId: "html-css",
      worldId: "interface-reactor",
    },
  },
  {
    id: "contract-artificer",
    name: "Contract Artificer",
    description: "Restore the Java Contract Forge.",
    rarity: "rare",
    icon: "fragment",
    condition: {
      type: "world-completed",
      trackId: "java",
      worldId: "contract-forge",
    },
  },
  {
    id: "lifetime-architect",
    name: "Lifetime Architect",
    description: "Restore the C++ Ownership Reactor.",
    rarity: "rare",
    icon: "core",
    condition: {
      type: "world-completed",
      trackId: "cpp",
      worldId: "ownership-reactor",
    },
  },
  {
    id: "deep-field-index",
    name: "Deep Field Index",
    description: "Restore seventy-five lesson fragments across the archive.",
    rarity: "mythic",
    icon: "network",
    condition: { type: "lesson-count", count: 75 },
  },
  {
    id: "complete-nexus",
    name: "Complete Nexus",
    description: "Restore the original ninety archive lesson fragments.",
    rarity: "mythic",
    icon: "core",
    condition: { type: "lesson-count", count: 90 },
    discoveryText: "The archive is no longer dormant. Every language sector answers.",
  },

  {
    id: "observatory-cartographer",
    name: "Observatory Cartographer",
    description:
      "Restore one hundred twenty lesson fragments across the expanded v5 observatory.",
    rarity: "mythic",
    icon: "network",
    condition: { type: "lesson-count", count: 120 },
    discoveryText:
      "The archive has become a working observatory of connected programming knowledge.",
  },
  {
    id: "singularity-reactor",
    name: "Singularity Reactor",
    description: "Accumulate 5,000 units of Signal Energy.",
    rarity: "mythic",
    icon: "conductor",
    condition: { type: "total-xp", amount: 5000 },
  },
];
