import type { BonusTask, Task, World } from "../../types";
import {
  createCurriculumLesson,
  type CurriculumLessonSpec,
  type CurriculumWorldSpec,
} from "../_shared/defineLesson";

function outputTask(
  id: string,
  title: string,
  description: string,
  expectedBehavior: string,
  starterCode: string,
  expected: string,
  hints: string[],
  defaultInput?: string,
): Task {
  return {
    id,
    title,
    description,
    expectedBehavior,
    starterCode,
    hints,
    validation: { mode: "trimmed-exact", expected },
    ...(defaultInput ? { defaultInput } : {}),
  };
}

function outputBonus(
  id: string,
  title: string,
  description: string,
  expectedBehavior: string,
  starterCode: string,
  expected: string,
  hints: string[],
  discoveryText: string,
  defaultInput?: string,
): BonusTask {
  return {
    ...outputTask(
      id,
      title,
      description,
      expectedBehavior,
      starterCode,
      expected,
      hints,
      defaultInput,
    ),
    discoveryText,
  };
}

const worlds: CurriculumWorldSpec[] = [
  {
    id: "data-currents",
    title: "Data Currents",
    subtitle: "Transform, protect, and route larger streams of information",
    description:
      "Compact transformations, error recovery, standard modules, text parsing, and staged pipelines turn raw signals into reliable data.",
    landmark: "The Flow Observatory",
    accent: "cyan",
    lessons: [
      {
        id: "python-comprehensions",
        title: "Compressed Currents",
        subtitle: "Build readable collections with comprehensions",
        objectives: [
          "Create lists with expression-for syntax",
          "Filter values with a trailing condition",
          "Choose when a normal loop is clearer",
        ],
        conceptHeading: "A comprehension describes a collection transformation",
        explanation: [
          "A list comprehension combines the result expression, source sequence, and optional filter in one readable statement. It is ideal when each input value independently produces zero or one output value.",
          "Compact is not automatically clear. Keep multi-stage decisions in ordinary loops and use comprehensions for transformations that can be understood from left to right.",
        ],
        bullets: [
          "Start with the output expression.",
          "Add for name in source.",
          "Add an optional if condition at the end.",
        ],
        syntax: "[expression for item in source if condition]",
        example: {
          title: "Recover high-energy readings",
          description: "The filter keeps readings at or above 50 before doubling them.",
          code: "readings = [18, 52, 71, 33]\nboosted = [value * 2 for value in readings if value >= 50]\nprint(boosted)",
          output: "[104, 142]",
        },
        fieldNote:
          "Read the comprehension aloud as a sentence. If the sentence becomes tangled, expand it into a loop.",
        mistakes: [
          "Placing the filter before the for clause.",
          "Using a comprehension only for side effects such as print().",
          "Packing nested loops and several conditions into one unreadable line.",
        ],
        tasks: [
          outputTask(
            "python-comprehensions-squares",
            "Square the sequence",
            "Create a comprehension that squares 1 through 4, then print the values joined by commas.",
            "The output is 1,4,9,16.",
            'numbers = [1, 2, 3, 4]\n# Build squares with one comprehension\nsquares = []\nprint(",".join(str(value) for value in squares))',
            "1,4,9,16",
            ["The expression is number ** 2."],
          ),
          outputTask(
            "python-comprehensions-filter",
            "Filter even signals",
            "Use one comprehension to keep the even values from 1 through 7.",
            "Print 2|4|6.",
            'values = range(1, 8)\n# Keep only values divisible by 2\nevens = []\nprint("|".join(str(value) for value in evens))',
            "2|4|6",
            ["A number is even when number % 2 == 0."],
          ),
        ],
        bonusTask: outputBonus(
          "python-comprehensions-bonus",
          "Positive-square decoder",
          "Read comma-separated integers, keep only positive values, square them, sort the squares, and print them separated by spaces.",
          "For -2, 5, 3, 0, 2 print 4 9 25.",
          "raw = input()\n# Decode, filter, transform, sort, and report\n",
          "4 9 25",
          [
            "Split on commas and convert each stripped fragment with int().",
            "sorted(...) can order the completed comprehension.",
          ],
          "A compact transformation channel opens beneath the Flow Observatory.",
          "-2, 5, 3, 0, 2",
        ),
      },
      {
        id: "python-exceptions",
        title: "Fault Containment",
        subtitle: "Recover from expected failures with exceptions",
        objectives: [
          "Catch a specific exception",
          "Separate successful and fallback paths",
          "Avoid hiding unrelated programming errors",
        ],
        conceptHeading: "Exceptions move control to a deliberate recovery path",
        explanation: [
          "Operations such as numeric conversion can fail for valid external reasons. A try block contains the risky operation; an except block handles a named failure without terminating the whole program.",
          "Catch the narrowest exception you expect. A broad except can conceal spelling mistakes, broken assumptions, and other defects that should remain visible.",
        ],
        bullets: [
          "Keep the try block small.",
          "Catch ValueError for failed numeric conversion.",
          "Use else for work that should run only after success.",
        ],
        syntax: "try:\n    risky_operation()\nexcept ValueError:\n    recover()",
        example: {
          title: "Decode uncertain readings",
          description: "Invalid numeric text receives a visible fallback marker.",
          code: 'for raw in ["8", "lost", "13"]:\n    try:\n        print(int(raw))\n    except ValueError:\n        print("?")',
          output: "8\n?\n13",
        },
        fieldNote:
          "An exception handler is part of the program contract: decide which failures are expected and what the learner should observe.",
        mistakes: [
          "Using bare except and hiding every error.",
          "Putting an entire program inside one try block.",
          "Reporting success from finally even when the operation failed.",
        ],
        tasks: [
          outputTask(
            "python-exceptions-convert",
            "Decode three readings",
            'Convert "12", "bad", and "7" to integers; print ? only for invalid text.',
            "Print 12, ?, and 7 on separate lines.",
            'for raw in ["12", "bad", "7"]:\n    # Convert safely\n    pass',
            "12\n?\n7",
            ["Catch ValueError around int(raw)."],
          ),
          outputTask(
            "python-exceptions-division",
            "Protect division",
            "For divisors 2 and 0, divide 10 and print undefined when division is impossible.",
            "Print 5.0 then undefined.",
            'for divisor in [2, 0]:\n    # Print a quotient or "undefined"\n    pass',
            "5.0\nundefined",
            ["Division by zero raises ZeroDivisionError."],
          ),
        ],
        bonusTask: outputBonus(
          "python-exceptions-bonus",
          "Batch intake report",
          "Read five space-separated tokens. Sum valid integers and report valid count, invalid count, and total.",
          "For 4 lost 9 ? 5 print VALID=3, INVALID=2, TOTAL=18.",
          "tokens = input().split()\nvalid = 0\ninvalid = 0\ntotal = 0\n# Recover every usable reading\n",
          "VALID=3\nINVALID=2\nTOTAL=18",
          ["Use one try/except inside the loop.", "Increment only the matching counter."],
          "The archive now distinguishes damaged data from damaged logic.",
          "4 lost 9 ? 5",
        ),
      },
      {
        id: "python-modules",
        title: "Module Constellations",
        subtitle: "Reuse focused tools from the standard library",
        objectives: [
          "Import a module or selected name",
          "Call names through a module namespace",
          "Apply math and statistics tools to real data",
        ],
        conceptHeading: "Modules organize reusable names behind explicit boundaries",
        explanation: [
          "Python's standard library contains tested tools for mathematics, statistics, text, dates, files, and many other tasks. import makes a module available without copying its implementation into your program.",
          "A module namespace such as math.sqrt explains where a name came from. Selective imports are useful when a small number of distinctive names are used repeatedly.",
        ],
        bullets: [
          "Prefer standard-library tools over rewriting established algorithms.",
          "Keep module imports at the top of a file.",
          "Avoid wildcard imports because they hide name origins.",
        ],
        syntax: "import math\nresult = math.sqrt(81)",
        example: {
          title: "Measure a signal vector",
          description: "hypot calculates a two-dimensional distance.",
          code: "import math\nlength = math.hypot(3, 4)\nprint(length)",
          output: "5.0",
        },
        fieldNote:
          "Before adding a dependency, inspect the standard library. A built-in module is portable across every normal Python installation.",
        mistakes: [
          "Naming a local file math.py and shadowing the real module.",
          "Calling sqrt without importing it or qualifying it.",
          "Using random output where a deterministic result is required.",
        ],
        tasks: [
          outputTask(
            "python-modules-ceiling",
            "Round a root upward",
            "Use math.sqrt and math.ceil to calculate the ceiling of the square root of 70.",
            "Print 9.",
            "import math\n# Calculate with math.sqrt and math.ceil\n",
            "9",
            ["Nest math.sqrt(70) inside math.ceil(...)."],
          ),
          outputTask(
            "python-modules-mean",
            "Recover the mean",
            "Use statistics.mean for [4, 7, 8, 11].",
            "Print 7.5.",
            "import statistics\nreadings = [4, 7, 8, 11]\n# Print the arithmetic mean\n",
            "7.5",
            ["statistics.mean accepts the list directly."],
          ),
        ],
        bonusTask: outputBonus(
          "python-modules-bonus",
          "Circular chamber report",
          "Read a radius and print AREA and CIRCUMFERENCE rounded to two decimals using math.pi.",
          "For radius 3 print AREA=28.27 and CIRCUMFERENCE=18.85.",
          "import math\nradius = float(input())\n# Calculate and format both measurements\n",
          "AREA=28.27\nCIRCUMFERENCE=18.85",
          ["Use :.2f inside an f-string.", "Area is pi*r**2; circumference is 2*pi*r."],
          "A geometric calibration ring aligns with the archive core.",
          "3",
        ),
      },
      {
        id: "python-text-parsing",
        title: "Text Sediments",
        subtitle: "Split, normalize, and summarize structured text",
        objectives: [
          "Split text into meaningful fields",
          "Normalize whitespace and letter case",
          "Build stable reports from parsed values",
        ],
        conceptHeading: "Parsing turns raw text into data with a known shape",
        explanation: [
          "Text often arrives as lines, comma-separated fields, or labeled fragments. Parsing is the staged process of splitting a string, cleaning each part, validating it, and storing the result.",
          "Normalize at the boundary so later logic works with one consistent representation. Preserve the original text only when it is needed for display or auditing.",
        ],
        bullets: [
          "Split with the delimiter defined by the input format.",
          "Strip each field independently.",
          "Normalize case before counting categories.",
        ],
        syntax: 'fields = [part.strip() for part in raw.split(",")]',
        example: {
          title: "Decode a compact record",
          description: "The record becomes a normalized list of fields.",
          code: 'raw = " NX-7, Active , 84 "\nfields = [part.strip().lower() for part in raw.split(",")]\nprint("|".join(fields))',
          output: "nx-7|active|84",
        },
        fieldNote:
          "Parsing code should make malformed input visible rather than silently inventing missing fields.",
        mistakes: [
          "Calling strip() only on the complete line instead of each field.",
          "Splitting on spaces when fields themselves may contain spaces.",
          "Mixing parsing, business rules, and final formatting in one expression.",
        ],
        tasks: [
          outputTask(
            "python-text-parsing-fields",
            "Normalize CSV fields",
            'Parse "alpha, beta,ALPHA" and print lowercase fields joined by |.',
            "Print alpha|beta|alpha.",
            'raw = "alpha, beta,ALPHA"\n# Split, strip, lowercase, and join\n',
            "alpha|beta|alpha",
            ["Transform each part in a list comprehension."],
          ),
          outputTask(
            "python-text-parsing-frequency",
            "Count normalized words",
            'Count each word in "Core signal core map signal core" and print core then signal counts.',
            "Print core=3 and signal=2.",
            'text = "Core signal core map signal core"\ncounts = {}\n# Normalize and count words\nprint(f"core={counts.get(\'core\', 0)}")\nprint(f"signal={counts.get(\'signal\', 0)}")',
            "core=3\nsignal=2",
            ["Loop over text.lower().split()."],
          ),
        ],
        bonusTask: outputBonus(
          "python-text-parsing-bonus",
          "Status log decoder",
          "Read four lines formatted name:status. Normalize both fields and print active names in alphabetical order.",
          "For the supplied log print atlas, nexus, and prism on separate lines.",
          "records = []\nfor _ in range(4):\n    records.append(input())\n# Parse and report active names\n",
          "atlas\nnexus\nprism",
          ["Split each record once on ':'.", "Collect matching names, then sort them."],
          "A buried status ledger becomes searchable.",
          "Nexus:ACTIVE\nEcho:offline\nPrism:active\nAtlas: Active",
        ),
      },
      {
        id: "python-data-pipelines",
        title: "Pipeline Junction",
        subtitle: "Compose small transformations into a reliable data flow",
        objectives: [
          "Separate input, transformation, and reporting",
          "Use functions as pipeline stages",
          "Test intermediate representations",
        ],
        conceptHeading: "A pipeline gives each data stage one responsibility",
        explanation: [
          "A data pipeline receives raw values, normalizes them, filters unusable entries, transforms valid records, and reports a result. Named functions make these stages testable and replaceable.",
          "Keep the intermediate data shape predictable. When a stage accepts and returns a clearly defined value, the complete flow is easier to reason about.",
        ],
        bullets: [
          "Parse external text at the boundary.",
          "Keep calculations independent from print().",
          "Format only in the final reporting stage.",
        ],
        syntax: "report(transform(filter(parse(raw))))",
        example: {
          title: "Three-stage energy pipeline",
          description: "Normalization, filtering, and transformation remain visible.",
          code: 'raw = [" 4", "lost", " 9"]\nvalid = [int(item) for item in raw if item.strip().isdigit()]\nenergy = [value * 10 for value in valid]\nprint(sum(energy))',
          output: "130",
        },
        fieldNote:
          "When a result is wrong, print or test the output of one stage at a time instead of debugging the full pipeline at once.",
        mistakes: [
          "Changing the data type unexpectedly between stages.",
          "Printing from every helper and creating duplicate output.",
          "Using one function for parsing, filtering, calculating, and formatting.",
        ],
        tasks: [
          outputTask(
            "python-data-pipelines-clean",
            "Clean and aggregate",
            'From [" 4 ", "-1", "bad", " 6"], keep digit-only values, convert them, and print their sum.',
            "Print 10.",
            'raw = [" 4 ", "-1", "bad", " 6"]\n# Normalize, validate, convert, and aggregate\n',
            "10",
            ["strip().isdigit() identifies the two accepted values."],
          ),
          outputTask(
            "python-data-pipelines-functions",
            "Compose named stages",
            "Complete normalize and boost, then transform [2, 5, 8] and print 4|10|16.",
            "Print 4|10|16.",
            'def normalize(values):\n    # Return integer values\n    pass\n\ndef boost(values):\n    # Double every value\n    pass\n\nresult = boost(normalize([2, 5, 8]))\nprint("|".join(str(value) for value in result))',
            "4|10|16",
            ["Each helper should return a new list."],
          ),
        ],
        bonusTask: outputBonus(
          "python-data-pipelines-bonus",
          "Sensor pipeline",
          "Read comma-separated readings, ignore invalid tokens, keep values from 0 to 100, and report count, mean, and maximum.",
          "For 10, lost, 120, 30, 50 print COUNT=3, MEAN=30.0, MAX=50.",
          "raw = input()\n# Parse safely, filter range, calculate, and report\n",
          "COUNT=3\nMEAN=30.0\nMAX=50",
          [
            "Use try/except while parsing tokens.",
            "Calculate only after the valid list is complete.",
          ],
          "The Flow Observatory begins routing live telemetry.",
          "10, lost, 120, 30, 50",
        ),
      },
    ],
  },
  {
    id: "object-foundry",
    title: "Object Foundry",
    subtitle: "Model state and behavior as cooperating objects",
    description:
      "Classes turn related data and behavior into reusable blueprints, then connect those objects through clear contracts.",
    landmark: "The Blueprint Crucible",
    accent: "violet",
    lessons: [
      {
        id: "python-classes",
        title: "Blueprint Specimens",
        subtitle: "Define classes and initialize independent objects",
        objectives: [
          "Define a class with __init__",
          "Store data on self",
          "Create multiple independent instances",
        ],
        conceptHeading: "A class is a blueprint; an object is one constructed specimen",
        explanation: [
          "A class describes which attributes and behaviors its objects share. The __init__ method receives the new object as self and assigns the starting state.",
          "Each instance owns its own attribute values. Changing one specimen should not silently change another unless the data is deliberately shared at class level.",
        ],
        bullets: [
          "Class names conventionally use PascalCase.",
          "Every instance method receives self first.",
          "Assign constructor parameters to self attributes.",
        ],
        syntax:
          "class Signal:\n    def __init__(self, strength):\n        self.strength = strength",
        example: {
          title: "Construct two signals",
          description: "Both objects share a blueprint but keep separate state.",
          code: 'class Signal:\n    def __init__(self, name, strength):\n        self.name = name\n        self.strength = strength\n\nfirst = Signal("NX", 80)\nsecond = Signal("Echo", 45)\nprint(first.strength, second.strength)',
          output: "80 45",
        },
        fieldNote:
          "Choose classes when several values and behaviors form one durable concept, not merely to wrap a single calculation.",
        mistakes: [
          "Forgetting self in the method signature.",
          "Assigning to a local name instead of self.attribute.",
          "Reading an attribute before __init__ creates it.",
        ],
        tasks: [
          outputTask(
            "python-classes-create",
            "Construct a relic",
            "Define Relic with name and energy attributes, create Relic('Prism', 88), and print Prism:88.",
            "Print Prism:88.",
            'class Relic:\n    # Add a constructor\n    pass\n\nrelic = Relic("Prism", 88)\nprint(f"{relic.name}:{relic.energy}")',
            "Prism:88",
            ["Assign both constructor parameters to self."],
          ),
          outputTask(
            "python-classes-independent",
            "Preserve independent state",
            "Create two Counter objects with values 3 and 9, change only the first to 4, then print both values.",
            "Print 4 9.",
            "class Counter:\n    def __init__(self, value):\n        # Store value\n        pass\n\nfirst = Counter(3)\nsecond = Counter(9)\n# Change only first\nprint(first.value, second.value)",
            "4 9",
            ["Set first.value directly after construction."],
          ),
        ],
        bonusTask: outputBonus(
          "python-classes-bonus",
          "Coordinate specimen",
          "Create Point objects with x and y. Add a describe method returning (x,y), then report points (2,5) and (-1,3).",
          "Print (2,5) then (-1,3).",
          "class Point:\n    # Constructor and describe method\n    pass\n\nfor point in [Point(2, 5), Point(-1, 3)]:\n    print(point.describe())",
          "(2,5)\n(-1,3)",
          ["Return an f-string from describe; do not print inside it."],
          "The foundry recognizes the first user-defined blueprint.",
        ),
      },
      {
        id: "python-methods",
        title: "Behavior Chambers",
        subtitle: "Let methods read and change object state",
        objectives: [
          "Define instance methods",
          "Update state through behavior",
          "Return useful values from methods",
        ],
        conceptHeading: "Methods keep state changes beside the rules that govern them",
        explanation: [
          "An instance method can read and update the object through self. Instead of scattering attribute changes across a program, methods name the allowed operations.",
          "A method may mutate state, return a value, or do both. Clear method names and small responsibilities make object interactions understandable.",
        ],
        bullets: [
          "Use verbs for behavior names.",
          "Protect invariants inside the method.",
          "Return data when callers need to compose further work.",
        ],
        syntax:
          "def charge(self, amount):\n    self.energy += amount\n    return self.energy",
        example: {
          title: "Charge one cell",
          description: "The method owns the energy update.",
          code: "class Cell:\n    def __init__(self, energy):\n        self.energy = energy\n\n    def charge(self, amount):\n        self.energy += amount\n        return self.energy\n\ncell = Cell(30)\nprint(cell.charge(12))",
          output: "42",
        },
        fieldNote:
          "If every caller must remember the same validation rule, move that rule into the object's method.",
        mistakes: [
          "Updating a local variable instead of self state.",
          "Calling a method without parentheses.",
          "Returning before the state update can run.",
        ],
        tasks: [
          outputTask(
            "python-methods-charge",
            "Charge a battery",
            "Complete Battery.charge so it adds energy but never exceeds 100. Charge 85 by 30.",
            "Print 100.",
            "class Battery:\n    def __init__(self, energy):\n        self.energy = energy\n\n    def charge(self, amount):\n        # Add with an upper limit\n        pass\n\nbattery = Battery(85)\nprint(battery.charge(30))",
            "100",
            ["min(100, self.energy + amount) applies the cap."],
          ),
          outputTask(
            "python-methods-consume",
            "Consume only available energy",
            "Implement consume(amount): subtract and return True when enough energy exists; otherwise leave state unchanged and return False.",
            "For energy 20 and requests 7 then 15, print True:13 and False:13.",
            'class Cell:\n    def __init__(self, energy):\n        self.energy = energy\n\n    def consume(self, amount):\n        # Apply the rule\n        pass\n\ncell = Cell(20)\nprint(f"{cell.consume(7)}:{cell.energy}")\nprint(f"{cell.consume(15)}:{cell.energy}")',
            "True:13\nFalse:13",
            ["Check amount <= self.energy before subtracting."],
          ),
        ],
        bonusTask: outputBonus(
          "python-methods-bonus",
          "Inventory object",
          "Create Inventory with add(name) and count(name). Add prism, key, prism and report prism=2 and key=1.",
          "Print prism=2 then key=1.",
          'class Inventory:\n    def __init__(self):\n        self.items = []\n\n    # Add both methods\n\ninventory = Inventory()\nfor name in ["prism", "key", "prism"]:\n    inventory.add(name)\nprint(f"prism={inventory.count(\'prism\')}")\nprint(f"key={inventory.count(\'key\')}")',
          "prism=2\nkey=1",
          ["list.append and list.count are enough for this version."],
          "A behavior lattice activates around the Blueprint Crucible.",
        ),
      },
      {
        id: "python-properties",
        title: "Invariant Shields",
        subtitle: "Protect valid state with properties",
        objectives: [
          "Define a property getter",
          "Validate assignments in a setter",
          "Preserve an object's invariant",
        ],
        conceptHeading: "A property keeps attribute syntax while controlling access",
        explanation: [
          "A property exposes a calculated or protected value through normal attribute syntax. A setter can reject values that would make the object invalid.",
          "Store the internal value under a different name such as _energy so the property does not call itself recursively.",
        ],
        bullets: [
          "Use @property above the getter.",
          "Use @name.setter for controlled assignment.",
          "Raise ValueError when a caller violates the contract.",
        ],
        syntax: "@property\ndef energy(self):\n    return self._energy",
        example: {
          title: "Bounded signal strength",
          description: "The setter enforces a range for every assignment.",
          code: 'class Signal:\n    def __init__(self, strength):\n        self.strength = strength\n\n    @property\n    def strength(self):\n        return self._strength\n\n    @strength.setter\n    def strength(self, value):\n        if not 0 <= value <= 100:\n            raise ValueError("out of range")\n        self._strength = value\n\nprint(Signal(75).strength)',
          output: "75",
        },
        fieldNote:
          "Use a property for a real invariant or computed value, not automatically for every attribute.",
        mistakes: [
          "Assigning self.energy inside the energy setter and causing recursion.",
          "Silently clipping invalid data when the caller should know it failed.",
          "Creating a setter whose validation differs from the constructor.",
        ],
        tasks: [
          outputTask(
            "python-properties-temperature",
            "Protect temperature",
            "Create a celsius property that rejects values below -273.15. Print 20, then catch and print invalid for -300.",
            "Print 20 then invalid.",
            'class Sensor:\n    def __init__(self, celsius):\n        self.celsius = celsius\n\n    # Add getter and validated setter\n\nsensor = Sensor(20)\nprint(sensor.celsius)\ntry:\n    sensor.celsius = -300\nexcept ValueError:\n    print("invalid")',
            "20\ninvalid",
            ["Store accepted values in self._celsius."],
          ),
          outputTask(
            "python-properties-computed",
            "Expose a computed label",
            "Add a read-only label property returning name.upper() plus # plus id.",
            "For prism and 7 print PRISM#7.",
            'class Relic:\n    def __init__(self, name, relic_id):\n        self.name = name\n        self.relic_id = relic_id\n\n    # Add read-only label property\n\nprint(Relic("prism", 7).label)',
            "PRISM#7",
            ["A property can return an f-string without a setter."],
          ),
        ],
        bonusTask: outputBonus(
          "python-properties-bonus",
          "Bounded progress meter",
          "Create Progress.value property accepting only integers from 0 to 100. Apply 10, 55, 130 and print accepted values or rejected.",
          "Print 10, 55, rejected.",
          'class Progress:\n    def __init__(self, value):\n        self.value = value\n\n    # Add property contract\n\nprogress = Progress(0)\nfor value in [10, 55, 130]:\n    try:\n        progress.value = value\n        print(progress.value)\n    except ValueError:\n        print("rejected")',
          "10\n55\nrejected",
          ["Check type(value) is int as well as the numeric range."],
          "The foundry seals its first state invariant.",
        ),
      },
      {
        id: "python-inheritance",
        title: "Ancestral Interfaces",
        subtitle: "Share behavior through inheritance and polymorphism",
        objectives: [
          "Derive a subclass from a base class",
          "Override a method",
          "Call different objects through one interface",
        ],
        conceptHeading: "Polymorphism lets different objects answer the same message",
        explanation: [
          "A subclass inherits accessible behavior from its base class and can override selected methods. Callers can then use the shared method name without inspecting each concrete type.",
          "Inheritance is strongest when the subclass truly is a specialized form of the base concept. For simple reuse between unrelated concepts, composition is usually clearer.",
        ],
        bullets: [
          "Declare class Child(Parent).",
          "Keep the shared contract stable across overrides.",
          "Use super() when extending base initialization.",
        ],
        syntax: 'class Pulse(Signal):\n    def describe(self):\n        return "pulse"',
        example: {
          title: "Two signal descriptions",
          description: "One loop uses a shared method on different subclasses.",
          code: 'class Signal:\n    def describe(self):\n        return "signal"\n\nclass Pulse(Signal):\n    def describe(self):\n        return "pulse"\n\nfor item in [Signal(), Pulse()]:\n    print(item.describe())',
          output: "signal\npulse",
        },
        fieldNote:
          "Design the common interface first. Inheritance should express meaning, not just save a few lines.",
        mistakes: [
          "Changing an overridden method's meaning unexpectedly.",
          "Forgetting super().__init__ when base state is required.",
          "Building deep inheritance chains that are hard to trace.",
        ],
        tasks: [
          outputTask(
            "python-inheritance-override",
            "Override a transmission",
            'Create LoudSignal(Signal) whose emit returns the base message uppercased. Print "CORE".',
            "Print CORE.",
            'class Signal:\n    def emit(self):\n        return "core"\n\nclass LoudSignal(Signal):\n    # Override emit\n    pass\n\nprint(LoudSignal().emit())',
            "CORE",
            ["You may call super().emit().upper()."],
          ),
          outputTask(
            "python-inheritance-polymorphism",
            "Use one interface",
            "Create Circle.area and Square.area, then loop over both and print their areas as integers.",
            "For radius 2 and side 3 print 12 then 9.",
            "class Circle:\n    def __init__(self, radius):\n        self.radius = radius\n\n    def area(self):\n        # Use 3 for pi in this exercise\n        pass\n\nclass Square:\n    def __init__(self, side):\n        self.side = side\n\n    def area(self):\n        pass\n\nfor shape in [Circle(2), Square(3)]:\n    print(shape.area())",
            "12\n9",
            ["Both classes need the same method name."],
          ),
        ],
        bonusTask: outputBonus(
          "python-inheritance-bonus",
          "Notification relay",
          "Create Email and Console subclasses of Notifier. Their send methods return EMAIL:<message> and CONSOLE:<message>.",
          "For message online print both labeled lines.",
          'class Notifier:\n    def send(self, message):\n        raise NotImplementedError\n\nclass Email(Notifier):\n    pass\n\nclass Console(Notifier):\n    pass\n\nfor notifier in [Email(), Console()]:\n    print(notifier.send("online"))',
          "EMAIL:online\nCONSOLE:online",
          ["Override send in each subclass with the same parameter list."],
          "Multiple object lineages synchronize through one interface.",
        ),
      },
      {
        id: "python-dataclasses",
        title: "Foundry Assembly",
        subtitle: "Build concise data objects and an object-oriented capstone",
        objectives: [
          "Declare a @dataclass",
          "Add behavior to generated data objects",
          "Coordinate a collection of objects",
        ],
        conceptHeading: "Dataclasses remove repetitive setup from data-centered classes",
        explanation: [
          "The @dataclass decorator generates an initializer and useful representation from declared fields. The class can still define methods, validation hooks, and computed properties.",
          "Dataclasses suit records whose identity is primarily their data. A behavior-heavy service object may still need an explicit constructor and carefully controlled state.",
        ],
        bullets: [
          "Import dataclass from dataclasses.",
          "Declare fields with type annotations.",
          "Use normal methods for derived behavior.",
        ],
        syntax: "@dataclass\nclass Reading:\n    name: str\n    value: int",
        example: {
          title: "Compact reading record",
          description: "Generated initialization combines with a normal method.",
          code: 'from dataclasses import dataclass\n\n@dataclass\nclass Reading:\n    name: str\n    value: int\n\n    def active(self):\n        return self.value >= 50\n\nprint(Reading("NX", 72).active())',
          output: "True",
        },
        fieldNote:
          "Type annotations document expected data, but ordinary Python does not enforce them automatically at runtime.",
        mistakes: [
          "Forgetting the @ before dataclass.",
          "Using mutable list defaults instead of field(default_factory=list).",
          "Assuming annotations automatically reject incorrect runtime types.",
        ],
        tasks: [
          outputTask(
            "python-dataclasses-record",
            "Declare a specimen record",
            "Create @dataclass Specimen with name:str and energy:int, then print Prism:88.",
            "Print Prism:88.",
            'from dataclasses import dataclass\n\n# Declare Specimen\n\nspecimen = Specimen("Prism", 88)\nprint(f"{specimen.name}:{specimen.energy}")',
            "Prism:88",
            ["Place @dataclass immediately above the class."],
          ),
          outputTask(
            "python-dataclasses-method",
            "Add derived behavior",
            "Give Reading a band method returning high for 80+, stable for 40+, faint otherwise.",
            "For 91, 55, 12 print high, stable, faint.",
            "from dataclasses import dataclass\n\n@dataclass\nclass Reading:\n    value: int\n\n    def band(self):\n        # Classify self.value\n        pass\n\nfor value in [91, 55, 12]:\n    print(Reading(value).band())",
            "high\nstable\nfaint",
            ["Check thresholds from highest to lowest."],
          ),
        ],
        bonusTask: outputBonus(
          "python-dataclasses-bonus",
          "Foundry catalog",
          "Create a Relic dataclass with name and energy plus is_rare() for energy >= 80. Sort three relics by energy descending and label rare ones with *.",
          "Print Prism:88*, Coil:61, Key:30.",
          'from dataclasses import dataclass\n\n# Define Relic and is_rare\n\nrelics = [Relic("Key", 30), Relic("Prism", 88), Relic("Coil", 61)]\n# Sort and report\n',
          "Prism:88*\nCoil:61\nKey:30",
          ["sorted accepts key=lambda relic: relic.energy and reverse=True."],
          "The Blueprint Crucible completes a catalog of living objects.",
        ),
      },
    ],
  },
  {
    id: "algorithm-observatory",
    title: "Algorithm Observatory",
    subtitle: "Reason about search, order, recursion, and computational cost",
    description:
      "Algorithms become observable instruments: compare costs, search ordered data, sort by meaning, and decompose recursive structures.",
    landmark: "The Complexity Orrery",
    accent: "amber",
    lessons: [
      {
        id: "python-complexity",
        title: "Cost Signatures",
        subtitle: "Recognize how work grows with input size",
        objectives: [
          "Distinguish constant and linear work",
          "Choose sets for repeated membership checks",
          "Measure operations rather than guessing",
        ],
        conceptHeading: "Complexity describes growth, not a stopwatch result",
        explanation: [
          "Algorithmic complexity asks how required work changes as input grows. Accessing one list index is constant-time; scanning every element is linear-time.",
          "Data structure choice can change the dominant cost. A set usually provides much faster repeated membership checks than scanning a list.",
        ],
        bullets: [
          "O(1) work stays roughly constant.",
          "O(n) work grows with the number of items.",
          "Prefer clear code until scale makes the distinction meaningful.",
        ],
        syntax: "seen = set(values)\nif target in seen:\n    ...",
        example: {
          title: "Count a visible scan",
          description: "The counter makes the linear number of checks observable.",
          code: "checks = 0\nfor value in [4, 8, 15, 16, 23, 42]:\n    checks += 1\n    if value == 16:\n        break\nprint(checks)",
          output: "4",
        },
        fieldNote:
          "Optimize the operation that dominates real input sizes; avoid making code obscure for a theoretical improvement that cannot matter.",
        mistakes: [
          "Treating Big O as an exact runtime in milliseconds.",
          "Ignoring the cost of constructing a supporting data structure.",
          "Optimizing before correctness and measurement.",
        ],
        tasks: [
          outputTask(
            "python-complexity-membership",
            "Build a lookup set",
            "Convert the identifiers to a set and print whether NX-4 and NX-9 exist.",
            "Print True then False.",
            'identifiers = ["NX-1", "NX-2", "NX-4", "NX-7"]\n# Build one lookup structure\n\nprint("NX-4" in lookup)\nprint("NX-9" in lookup)',
            "True\nFalse",
            ["set(identifiers) creates the lookup."],
          ),
          outputTask(
            "python-complexity-count",
            "Expose scan cost",
            "Scan values until 25 appears and print the number of comparisons.",
            "For [3, 8, 13, 21, 25, 34] print 5.",
            "values = [3, 8, 13, 21, 25, 34]\nchecks = 0\n# Scan and stop at 25\nprint(checks)",
            "5",
            ["Increment before checking, then break."],
          ),
        ],
        bonusTask: outputBonus(
          "python-complexity-bonus",
          "Duplicate detector",
          "Read space-separated identifiers and use a set to print the first duplicate, or UNIQUE.",
          "For A7 B2 C9 B2 A7 print B2.",
          "identifiers = input().split()\nseen = set()\n# Stop at the first duplicate\n",
          "B2",
          [
            "If an identifier is already in seen, print it and break.",
            "A loop else can report UNIQUE.",
          ],
          "The orrery displays its first measurable cost curve.",
          "A7 B2 C9 B2 A7",
        ),
      },
      {
        id: "python-searching",
        title: "Search Beacons",
        subtitle: "Implement linear and binary search",
        objectives: [
          "Return a target index from linear search",
          "Apply binary search to sorted data",
          "State the precondition for binary search",
        ],
        conceptHeading: "Search strategies trade prerequisites for fewer checks",
        explanation: [
          "Linear search works on any sequence by checking values in order. Binary search repeatedly discards half of a sorted search region.",
          "Binary search is only correct when the data is ordered by the same key used for comparison. Record left, right, and midpoint carefully to avoid skipped values.",
        ],
        bullets: [
          "Linear search is simple and works on unsorted data.",
          "Binary search requires sorted data.",
          "Return a clear sentinel such as -1 when absent.",
        ],
        syntax: "middle = (left + right) // 2",
        example: {
          title: "Linear beacon",
          description: "enumerate provides both index and value.",
          code: "def locate(values, target):\n    for index, value in enumerate(values):\n        if value == target:\n            return index\n    return -1\n\nprint(locate([8, 3, 9], 3))",
          output: "1",
        },
        fieldNote:
          "Test search algorithms with the first item, last item, middle item, missing item, and an empty collection.",
        mistakes: [
          "Applying binary search to unsorted input.",
          "Updating left or right without moving past the midpoint.",
          "Forgetting the missing-target return path.",
        ],
        tasks: [
          outputTask(
            "python-searching-linear",
            "Complete linear search",
            "Return the index of target or -1. Search [14, 7, 22, 5] for 22 and 9.",
            "Print 2 then -1.",
            "def locate(values, target):\n    # Implement linear search\n    pass\n\nprint(locate([14, 7, 22, 5], 22))\nprint(locate([14, 7, 22, 5], 9))",
            "2\n-1",
            ["enumerate supplies the current index."],
          ),
          outputTask(
            "python-searching-binary",
            "Complete binary search",
            "Implement binary search and locate 23 and 4 in [3,8,12,23,31,44].",
            "Print 3 then -1.",
            "def binary_search(values, target):\n    left = 0\n    right = len(values) - 1\n    # Narrow the inclusive interval\n    return -1\n\nvalues = [3, 8, 12, 23, 31, 44]\nprint(binary_search(values, 23))\nprint(binary_search(values, 4))",
            "3\n-1",
            ["Loop while left <= right.", "Move to middle + 1 or middle - 1."],
          ),
        ],
        bonusTask: outputBonus(
          "python-searching-bonus",
          "Call-sign directory",
          "Given sorted (id,name) pairs, implement binary lookup by numeric id and report 31 then 18.",
          "Print Atlas then NOT FOUND.",
          'records = [(7, "Echo"), (12, "Nexus"), (31, "Atlas"), (44, "Prism")]\n\ndef find_name(records, target_id):\n    # Binary search by records[middle][0]\n    pass\n\nprint(find_name(records, 31))\nprint(find_name(records, 18))',
          "Atlas\nNOT FOUND",
          ["Return the name on a match and NOT FOUND after the loop."],
          "Search beacons synchronize across the ordered archive.",
        ),
      },
      {
        id: "python-sorting",
        title: "Ordering Lenses",
        subtitle: "Sort records by the field that carries meaning",
        objectives: [
          "Use sorted without mutating the source",
          "Define a key function",
          "Apply stable multi-field ordering",
        ],
        conceptHeading: "A sort key maps each record to its comparison value",
        explanation: [
          "sorted returns a new ordered list. The key function extracts the value that should determine order, such as energy, name length, or a tuple of several fields.",
          "Python sorting is stable: records with equal keys retain their previous relative order. Tuple keys make ascending multi-field rules explicit.",
        ],
        bullets: [
          "Use reverse=True for descending order.",
          "Use lambda for a small local key.",
          "Use a named function when the key logic deserves explanation.",
        ],
        syntax: "ordered = sorted(records, key=lambda item: item[1], reverse=True)",
        example: {
          title: "Order relics by energy",
          description: "The key selects the numeric field instead of the whole tuple.",
          code: 'relics = [("key", 30), ("prism", 88), ("coil", 61)]\nordered = sorted(relics, key=lambda item: item[1], reverse=True)\nprint([name for name, _ in ordered])',
          output: "['prism', 'coil', 'key']",
        },
        fieldNote:
          "State the ordering rule in product language before encoding it as a key.",
        mistakes: [
          "Expecting sorted to change the original list.",
          "Sorting numeric text lexicographically.",
          "Using reverse when only one field should descend.",
        ],
        tasks: [
          outputTask(
            "python-sorting-energy",
            "Order by descending energy",
            "Sort the records by energy descending and print names.",
            "Print prism, coil, key on separate lines.",
            'records = [{"name": "key", "energy": 30}, {"name": "prism", "energy": 88}, {"name": "coil", "energy": 61}]\n# Sort by energy descending\nfor record in ordered:\n    print(record["name"])',
            "prism\ncoil\nkey",
            ['Use key=lambda record: record["energy"].'],
          ),
          outputTask(
            "python-sorting-multikey",
            "Apply a tuple key",
            "Sort codes first by length, then alphabetically.",
            "For NX7, A2, CORE, B1 print A2 B1 NX7 CORE.",
            'codes = ["NX7", "A2", "CORE", "B1"]\n# Sort with a tuple key\nprint(" ".join(ordered))',
            "A2 B1 NX7 CORE",
            ["The key can return (len(code), code)."],
          ),
        ],
        bonusTask: outputBonus(
          "python-sorting-bonus",
          "Leaderboard lens",
          "Sort players by score descending, then name ascending, and print rank. name score.",
          "Print 1. Atlas 90, 2. Prism 90, 3. Echo 72.",
          'players = [("Prism", 90), ("Echo", 72), ("Atlas", 90)]\n# Apply descending score and ascending name\n',
          "1. Atlas 90\n2. Prism 90\n3. Echo 72",
          [
            "A numeric field can descend by using -score in the tuple key.",
            "enumerate(..., start=1) supplies ranks.",
          ],
          "The archive resolves competing records into a stable order.",
        ),
      },
      {
        id: "python-recursion",
        title: "Recursive Echoes",
        subtitle: "Solve a structure through smaller versions of itself",
        objectives: [
          "Define a base case",
          "Make progress toward that base case",
          "Trace recursive return values",
        ],
        conceptHeading: "Recursion needs a stopping case and a smaller subproblem",
        explanation: [
          "A recursive function calls itself with a simpler input. The base case returns directly; other cases combine one piece of work with the answer to the smaller problem.",
          "Recursion is natural for nested structures and divide-and-conquer algorithms. Ordinary loops are often clearer for simple counting and large linear sequences.",
        ],
        bullets: [
          "Write the base case first.",
          "Prove each call gets closer to it.",
          "Track what each stack frame must return.",
        ],
        syntax: "def countdown(n):\n    if n == 0:\n        return\n    countdown(n - 1)",
        example: {
          title: "Recursive sum",
          description:
            "Each call contributes one value and delegates the remaining list.",
          code: "def total(values):\n    if not values:\n        return 0\n    return values[0] + total(values[1:])\n\nprint(total([3, 5, 8]))",
          output: "16",
        },
        fieldNote:
          "Use a debugger table with input, base-case result, and returned value to understand the call stack.",
        mistakes: [
          "Missing a reachable base case.",
          "Calling the function with unchanged input.",
          "Forgetting to return the recursive result.",
        ],
        tasks: [
          outputTask(
            "python-recursion-factorial",
            "Recover factorial",
            "Implement factorial with 0! = 1 and print factorial(5).",
            "Print 120.",
            "def factorial(n):\n    # Base case and recursive case\n    pass\n\nprint(factorial(5))",
            "120",
            ["For n > 0, return n * factorial(n - 1)."],
          ),
          outputTask(
            "python-recursion-nested",
            "Count nested integers",
            "Recursively count integers inside nested lists.",
            "For [1,[2,[3,4]],5] print 5.",
            "def count_numbers(value):\n    # Integers count as one; lists sum child counts\n    pass\n\nprint(count_numbers([1, [2, [3, 4]], 5]))",
            "5",
            ["Use isinstance(value, int) and isinstance(value, list)."],
          ),
        ],
        bonusTask: outputBonus(
          "python-recursion-bonus",
          "Nested archive depth",
          "Return the maximum list nesting depth, where a flat list has depth 1.",
          "Print 1 for [1,2], 3 for [1,[2,[3]]], and 0 for 7.",
          "def depth(value):\n    # Compute recursively\n    pass\n\nprint(depth([1, 2]))\nprint(depth([1, [2, [3]]]))\nprint(depth(7))",
          "1\n3\n0",
          ["Non-lists have depth 0.", "A list is 1 + the maximum child depth."],
          "Recursive echoes reveal the archive's nested geometry.",
        ),
      },
      {
        id: "python-algorithm-capstone",
        title: "Observatory Protocol",
        subtitle: "Combine data modeling and algorithms in a final analyzer",
        objectives: [
          "Model a multi-stage analytical problem",
          "Choose suitable search and sort operations",
          "Produce a deterministic summary",
        ],
        conceptHeading: "A capstone succeeds when its contracts are explicit",
        explanation: [
          "The Observatory Protocol integrates parsing, validation, objects, searching, sorting, and reporting. Define the input format and output order before implementing individual stages.",
          "Use small pure functions where possible. The final program should be understandable as a sequence of named transformations rather than one dense loop.",
        ],
        bullets: [
          "Represent each record with a dataclass.",
          "Reject malformed records at the boundary.",
          "Sort the accepted data only once before reporting.",
        ],
        syntax: "raw text → parsed records → validated records → ordered report",
        example: {
          title: "Deterministic ranking",
          description: "A tuple key encodes the complete ordering contract.",
          code: 'records = [("NX", 71), ("Atlas", 88), ("Prism", 88)]\nfor name, score in sorted(records, key=lambda item: (-item[1], item[0])):\n    print(name, score)',
          output: "Atlas 88\nPrism 88\nNX 71",
        },
        fieldNote:
          "Before coding, write one tiny example that covers valid data, invalid data, tied scores, and a missing query.",
        mistakes: [
          "Letting invalid records enter later stages.",
          "Depending on accidental input order for tied results.",
          "Mixing user-facing formatting into every processing function.",
        ],
        tasks: [
          outputTask(
            "python-algorithm-capstone-rank",
            "Rank valid records",
            "Parse the supplied name:score records, ignore invalid scores, sort by score descending then name, and print them.",
            "Print Atlas:88, Prism:88, NX:71.",
            'raw_records = ["NX:71", "lost:bad", "Prism:88", "Atlas:88"]\nrecords = []\n# Parse safely and rank deterministically\n',
            "Atlas:88\nPrism:88\nNX:71",
            ["Use try/except for int(score).", "Sort with (-score, name)."],
          ),
          outputTask(
            "python-algorithm-capstone-query",
            "Build a case-insensitive index",
            "Create a dictionary from names to scores and answer prism, echo, atlas in that order.",
            "Print 88, NOT FOUND, 88.",
            'records = [("NX", 71), ("Prism", 88), ("Atlas", 88)]\nqueries = ["prism", "echo", "atlas"]\n# Build one normalized lookup and answer queries\n',
            "88\nNOT FOUND\n88",
            ["Store keys with name.lower().", "dict.get can supply NOT FOUND."],
          ),
        ],
        bonusTask: outputBonus(
          "python-algorithm-capstone-bonus",
          "Complete Observatory analyzer",
          "Read five name,score lines. Ignore malformed or out-of-range scores, rank valid records, then print VALID, REJECTED, TOP, and AVERAGE.",
          "For the supplied records report VALID=3, REJECTED=2, TOP=Atlas:91, AVERAGE=78.0.",
          "from dataclasses import dataclass\n\n@dataclass\nclass Record:\n    name: str\n    score: int\n\nraw_records = [input() for _ in range(5)]\n# Parse, validate 0..100, rank, and summarize\n",
          "VALID=3\nREJECTED=2\nTOP=Atlas:91\nAVERAGE=78.0",
          [
            "Split once on comma and guard both parsing and range.",
            "The valid scores are 91, 77, and 66.",
          ],
          "The Complexity Orrery completes a full rotation; Python Core is now a six-sector expedition.",
          "Atlas,91\nBroken\nNexus,77\nEcho,140\nPrism,66",
        ),
        durationMinutes: 42,
      },
    ],
  },
];

export function createPythonExpansionWorlds(firstPrerequisite: string): World[] {
  let previousLessonId: string | undefined = firstPrerequisite;
  return worlds.map((world, worldIndex): World => {
    const lessons = world.lessons.map((lesson: CurriculumLessonSpec, lessonIndex) => {
      const built = createCurriculumLesson(
        "python",
        "python",
        world.id,
        lessonIndex + 1,
        lesson,
        previousLessonId,
      );
      previousLessonId = built.id;
      return built;
    });
    return {
      id: world.id,
      trackId: "python",
      order: worldIndex + 4,
      title: world.title,
      subtitle: world.subtitle,
      description: world.description,
      landmark: world.landmark,
      accent: world.accent,
      status: "available",
      lessons,
    };
  });
}
